### PR TITLE
Upgrade osm-auth to 2.5.0 (OAuth 2)

### PR DESCRIPTION
**Pull request by Binnette**
Hi @PanierAvide, I started working on an upgrade of osm-request to use osm-auth 2.5.0 (OAuth 2.0).

I upgraded also WebPack from 3 to 4. And try to upgrade babel and so on.

This is still a work in progress and I didn't tested it yet. But your Jest tests are still passing.

Should I continue this work ? If yes, feel free to give me any advice. If no, Can I use another JS lib to make requests to OSM (and changesets, etc) for my JS app that is already compatible with OAuth 2.0 ?

### CODE REVIEW

**Comment by PanierAvide** [comment]
Hi @Binnette thanks for your work ! As far as I know, there is no ready-to-use JS library to communicate with OSM API, so this one might be your best shot. If you have tested it enough, we can merge and do a release :wink:

**Comment by Binnette** [comment]
Hi @PanierAvide, no I didn't tested it yet. I will need to make a test with one of my JS app.
Also I still have some error with "npm run doc", I will try to address it

**Comment by PanierAvide** [comment]
OK no worries, you can take your time :wink: Let me know if I can be of any help

**Comment by PanierAvide** [comment]
Thanks for your PR, will take some time to review it in coming days.

For 2.1, best solution seem to be exposing the `_auth` object so people can use it directly.

**Review by PanierAvide — APPROVED** [review]

**Comment by PanierAvide** [comment]
After messing up the npm release, you'll be happy to know that osm-request@2.0.0 is available :grin: 

Thanks for your huge work on this :100:

**Pull request merged**
